//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentRent3ISP9_7.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufacturerProduct
    {
        public int IdManufacturerProduct { get; set; }
        public int IdProduct { get; set; }
        public int IdManufacturer { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Product Product { get; set; }
    }
}
